Accessibility: added language dropdown menu, additional captions, logging CVAR, fixes
luciusDXL/TheForceEngine pull request #308
Opened 2023-08-08 17:48 UTC by kevinfoley

- Added a new "Language" dropdown to the Accessibility menu which lets the player select a different subtitles file. It looks for files in the `Captions/` directory with file names in format `subtitles-XX.txt`, where XX is intended to be an ISO 639-1 language code (but currently can be anything). The dropdown just displays the file names for now.
- Added missing subtitles for Kyle's radio VO on M11 Imperial City
- Added CVAR `d_logSFXNames` (bool). When enabled, the name of each sound effect that plays is logged to the console. This is very helpful when you want to caption a sound effect but don't know the name of the effect.

2023-08-08 20:14 UTC, RC2225 commented
You probably should use TFE_PATHS::getPath() for populating the list with the files. At least on Linux it would not work without even when the file is in your working directory. 

Something like this. (Copied from the ModLoader) 
```
char captionsDir[TFE_MAX_PATH];
snprintf(captionsDir, TFE_MAX_PATH, "%sCaptions/", TFE_Paths::getPath(PATH_PROGRAM));
FileList dirList;
FileUtil::readDirectory(captionsDir, "txt", dirList);
		
```

2023-08-08 21:46 UTC, kevinfoley commented
@RC2225 I've updated it to search for subtitle files in the way that you suggested. I'm not sure exactly how #309 relates to this or how to fix it. Do the subtitles work on Linux in the current release (i.e. before I added the new dropdown?)

2023-08-10 19:51 UTC, luciusDXL commented
Thanks for the PR, I will go through it later today.

2023-08-13 19:02 UTC, RC2225 commented
> @RC2225 I've updated it to search for subtitle files in the way that you suggested. I'm not sure exactly how #309 relates to this or how to fix it. Do the subtitles work on Linux in the current release (i.e. before I added the new dropdown?)

Sorry for the confusion, was more a remark what might not work with what I copied / don't fully understand. Furthermore, yes, before the dropdown was added it worked, which I completely forgot to mention. I also tested it now with the old version and when installed in the corresponding folders, which I before never did. With the old version it works too, even when the binary and the "support data" is not in the same folder. I see that I  still have to learn much about how native (linux) apps works. :)

2023-08-24 08:21 UTC, mlauss2 commented on TheForceEngine/TFE_A11y/accessibility.cpp
> +		sprintf(docsCaptionsDir, "%sCaptions/", docsDir);
For better linux compatibility, please add
TFE_Paths::mapSystemPath(docsCaptionsDir);
in here (it's a noop on windows).

2023-08-24 08:30 UTC, mlauss2 commented on TheForceEngine/TFE_A11y/accessibility.cpp
> +		sprintf(programCaptionsDir, "%sCaptions/", programDir);
same here

2023-08-24 16:23 UTC, kevinfoley commented
@mlauss2 I received several emails about comments you'd left on the code, but the links in the emails don't work and I don't have any notifications on GitHub; did you retract your comments?

2023-08-24 16:57 UTC, mlauss2 commented
> @mlauss2 I received several emails about comments you'd left on the code, but the links in the emails don't work and I don't have any notifications on GitHub; did you retract your comments?

Yes, I commented on the subtitle paths wrt. Linux; but after looking closer again, the comments were wrong/too simplistic.

2023-09-22 00:08 UTC, luciusDXL approved these changes

2023-09-22 00:20 UTC, luciusDXL requested changes
It looks like filePathList.* is in the root directory along with main. It probably makes sense to either put it in A11Y since that is the namespace you use.

2023-09-22 00:58 UTC, luciusDXL approved these changes

2023-09-22 00:58 UTC, merged